### ISSUE TITLE
Proof revision

### ISSUE THREAD

**Issue by Ginko-X** [Ginko-X/Streaming_NESL#27]
When I try to prove Lemma 3.15, the last case `p=p1;p2` using Lemma 3.14, it seems not enough by just saying `forall s in fv(p).  σ(s) =  σ'(s)` . 

![image](https://user-images.githubusercontent.com/5687628/31853301-a314a11c-b686-11e7-9592-4ed4364dd499.png)

So I'm thinking about changing it like 
```
If <p, σ> ↓ σ'， then forall s _not_ in dv(p): σ'(s) = σ(s)
```
or 
```
If <p, σ> ↓ σ'， then forall s  in dom(σ): σ'(s) = σ(s)
```
I'm not sure if they are better or correct; the case `p=p1;p2` of proving the lemma itself is also a little bit weird.

And I think we need to add the condition "p is well-formed" to both of these lemmas, i.e.,3,14 and 3.15 (then maybe the concatenation lemma as well). Is that necessary?

**Comment by afilinski** [comment]
Yes, it seems to prove the p1;p2 case of 3.15, you need a stronger version of 3.14, which says that the entire "old" state is preserved by p1, not only the parts that p1 actually accesses. And both lemmas of course only hold for well-formed programs. The problem with strengthening 3.14 as you suggest is that there is then no formal connection between the well-formedness checking of a program (in terms of fv(p) and dv(p)) and the states sigma and sigma' at runtime.

I expect that the easiest fix will be to revise the judgment for well-formed programs (Def. 3.1) to talk about which streams _may_ appear free in a program, rather than about the ones that actually do. At the same time, we can also make the dv(p) function part of the judgment instead of defining it separately. That is, the new judgment form will be:

```
  S ||- p : S'
```
which says that the free variables of p are subset of S, and that the defined variables are exactly S'. I think the following rules should cover that:
```
  -----------------
  S ||- epsilon : Ø


  -------------------------------  ((s_i in S)^i=1..k, s not in S)
  S ||- s:=psi(s_1,...,s_k) : {s}

                S_in ||- p : S''               (s in S, S_in subset S,
  -------------------------------------------   S_out subset S'',
  S ||- S_out := WithCtrl(s, S_in, p) : S_out   S'' intersect S = Ø)


  S ||- p1 : S1    S U S1 ||- p2 : S2
  -----------------------------------
       S ||- p1; p2 : S1 U S2
```
Then you should still be able to show the lemma that if `S ||- p : S',` then `S intersect S' = Ø`. And I think that for some of the later theorems, it will be easier to work with S/S' rather than fv()/dv().
